# Apply: uninstall UWP packages from a plan JSON. Snapshots first.
# Runs winget uninstall / Remove-AppxPackage. Kills processes first.
# REQUIRES ADMIN for AllUsers removal (falls back to current-user if not admin).
#
# Plan JSON shape:
#   {
#     "remove": [
#       { "name": "Microsoft.BingWeather", "packageFullName": "Microsoft.BingWeather_4.53.51422.0_x64__8wekyb3d8bbwe", "reason": "Bing Weather" }
#     ]
#   }

param(
    [Parameter(Mandatory=$true)][string]$Plan,
    [string]$SnapshotDir
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '..\_lib\common.ps1')

if (-not $SnapshotDir) { $SnapshotDir = New-SnapshotDir -Module 'bloat' }
$log = Join-Path $SnapshotDir 'apply.log'
"===== bloat apply started $(Get-Date -Format o) =====" | Out-File $log -Encoding UTF8

# Snapshot: current package list for revert reference
$snap = Join-Path $SnapshotDir 'snapshot.json'
Get-AppxPackage | Select-Object Name, PackageFullName, Publisher, Version | ConvertTo-Json -Depth 3 | Set-Content $snap -Encoding UTF8
Write-Log $log 'SNAP' "Wrote $snap"

$planData = Get-Content $Plan -Raw | ConvertFrom-Json
$remove   = @($planData.remove)

$reverts = New-Object System.Collections.Generic.List[string]

foreach ($item in $remove) {
    $pkg = Get-AppxPackage -Name $item.name -ErrorAction SilentlyContinue
    if (-not $pkg) {
        Write-Log $log 'SKIP' "$($item.name) not installed"
        continue
    }
    # Kill any running processes belonging to this package
    Get-Process -ErrorAction SilentlyContinue | Where-Object {
        try { $_.MainModule.FileName -like "*$($pkg.InstallLocation)*" } catch { $false }
    } | ForEach-Object {
        Write-Log $log 'KILL' "$($_.Name) (PID $($_.Id)) belonging to $($item.name)"
        Stop-Process -Id $_.Id -Force -ErrorAction SilentlyContinue
    }

    # De-provision the app first (so it doesn't reinstall for new user profiles and current user removal is allowed).
    # Required for system-provisioned apps like Xbox, People, Feedback Hub - otherwise Remove-AppxPackage returns Access Denied.
    if (Test-Admin) {
        try {
            $prov = Get-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue | Where-Object { $_.DisplayName -eq $item.name }
            if ($prov) {
                Remove-AppxProvisionedPackage -Online -PackageName $prov.PackageName -ErrorAction Stop | Out-Null
                Write-Log $log 'DEPROV' "de-provisioned $($item.name)"
            }
        } catch {
            Write-Log $log 'WARN' "de-provision $($item.name): $($_.Exception.Message)"
        }
    }

    try {
        if (Test-Admin) {
            Remove-AppxPackage -Package $pkg.PackageFullName -AllUsers -ErrorAction Stop
        } else {
            Remove-AppxPackage -Package $pkg.PackageFullName -ErrorAction Stop
        }
        Write-Log $log 'APPLY' "removed $($item.name) - reason: $($item.reason)"
        $reverts.Add("# To reinstall: winget install --id <StoreID> or Add-AppxPackage with the .msix/.appx if you have it.")
        $reverts.Add("# $($item.name) was: $($pkg.PackageFullName)")
    } catch {
        Write-Log $log 'ERR' "$($item.name): $($_.Exception.Message)"
    }
}

# Emit revert script (best-effort — UWP reinstall requires the .msix/.appx or Store)
$revertScript = Join-Path $SnapshotDir 'revert.ps1'
$header = @"
# Auto-generated by pc-cleaner (bloat). UWP reinstall notes.
# To reinstall a removed Microsoft Store app:
#   winget install --id <StoreID>
# Or via Store URL, or (for provisioned apps only) via `Add-AppxProvisionedPackage`.
# The originals were:

"@
Set-Content -Path $revertScript -Value ($header + ($reverts -join "`n")) -Encoding UTF8

"===== bloat apply done $(Get-Date -Format o) =====" | Add-Content -Path $log
Write-Host "Snapshot dir: $SnapshotDir"
Write-Host "Revert notes: $revertScript"
