# Apply: Add Defender path exclusions from a plan JSON. NEVER touches RTP or scan schedule.
# REQUIRES ADMIN.

param(
    [Parameter(Mandatory=$true)][string]$Plan,
    [string]$SnapshotDir
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '..\_lib\common.ps1')
Assert-Admin

if (-not $SnapshotDir) { $SnapshotDir = New-SnapshotDir -Module 'defender' }
$log = Join-Path $SnapshotDir 'apply.log'
"===== defender apply started $(Get-Date -Format o) =====" | Out-File $log -Encoding UTF8

$planData = Get-Content $Plan -Raw | ConvertFrom-Json
$paths = @($planData.exclusionPaths)

# Snapshot: current exclusion list
$snap = Join-Path $SnapshotDir 'snapshot.json'
$before = @((Get-MpPreference).ExclusionPath)
$before | ConvertTo-Json | Set-Content $snap -Encoding UTF8
Write-Log $log 'SNAP' "$($before.Count) existing exclusions captured"

$added = New-Object System.Collections.Generic.List[string]
$reverts = New-Object System.Collections.Generic.List[string]

foreach ($p in $paths) {
    if ($before -contains $p) {
        Write-Log $log 'SKIP' "$p (already excluded)"
        continue
    }
    try {
        Add-MpPreference -ExclusionPath $p -ErrorAction Stop
        Write-Log $log 'APPLY' "Added exclusion: $p"
        $added.Add($p)
        $reverts.Add("Remove-MpPreference -ExclusionPath '$p'")
    } catch {
        Write-Log $log 'ERR' "$p : $($_.Exception.Message)"
    }
}

$revertScript = Join-Path $SnapshotDir 'revert.ps1'
$header = "# Auto-generated by pc-cleaner (defender). Removes exclusions added this run.`n# Never touches RTP status.`n`n"
Set-Content -Path $revertScript -Value ($header + ($reverts -join "`n")) -Encoding UTF8

"===== defender apply done: $($added.Count) exclusions added =====" | Add-Content -Path $log
Write-Host "Added $($added.Count) exclusions"
Write-Host "Revert: $revertScript"
