# Apply: Add Defender path exclusions from a plan JSON. NEVER touches RTP or scan schedule.
# REQUIRES ADMIN.

param(
    [Parameter(Mandatory=$true)][string]$Plan,
    [string]$SnapshotDir,
    [switch]$IKnowWhatImDoing
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '..\_lib\common.ps1')
Assert-Admin

if (-not $SnapshotDir) { $SnapshotDir = New-SnapshotDir -Module 'defender' }
$log = Join-Path $SnapshotDir 'apply.log'
"===== defender apply started $(Get-Date -Format o) =====" | Out-File $log -Encoding UTF8

$planData = Get-Content $Plan -Raw | ConvertFrom-Json
$paths = @($planData.exclusionPaths)

# Dangerous-path enforcement — added 2026-07-07 after audit. Some path patterns
# (drive roots, Downloads, TEMP, %USERPROFILE%) are the exact locations malware
# lands. Excluding them defeats Defender. Refuse unless -IKnowWhatImDoing.
$dangerousJson = Join-Path $PSScriptRoot '..\..\data\defender_dangerous_paths.json'
$dangerousPatterns = @()
$warnPatterns = @()
if (Test-Path $dangerousJson) {
    $dp = Get-Content $dangerousJson -Raw | ConvertFrom-Json
    $dangerousPatterns = @($dp.refuseUnlessOverride)
    $warnPatterns = @($dp.warnButAllow)
}
function Test-DangerousPath {
    param([string]$Path)
    $expanded = [Environment]::ExpandEnvironmentVariables($Path).TrimEnd('\')
    foreach ($p in $dangerousPatterns) {
        $pat = [Environment]::ExpandEnvironmentVariables($p.pattern).TrimEnd('\')
        if ($p.matchType -eq 'exact' -and $expanded -ieq $pat) { return $p }
        if ($p.matchType -eq 'prefix' -and $expanded -ilike "$pat*") { return $p }
    }
    return $null
}
function Test-WarnPath {
    param([string]$Path)
    foreach ($p in $warnPatterns) {
        if ($p.matchType -eq 'wildcard' -and $Path -ilike $p.pattern) { return $p }
    }
    return $null
}
$blockedExclusions = New-Object System.Collections.Generic.List[string]

# Snapshot: current exclusion list
$snap = Join-Path $SnapshotDir 'snapshot.json'
$before = @((Get-MpPreference).ExclusionPath)
$before | ConvertTo-Json | Set-Content $snap -Encoding UTF8
Write-Log $log 'SNAP' "$($before.Count) existing exclusions captured"

$added = New-Object System.Collections.Generic.List[string]
$reverts = New-Object System.Collections.Generic.List[string]

foreach ($p in $paths) {
    if ($before -contains $p) {
        Write-Log $log 'SKIP' "$p (already excluded)"
        continue
    }
    $danger = Test-DangerousPath $p
    if ($danger -and -not $IKnowWhatImDoing) {
        Write-Log $log 'BLOCK' "$p - refused: matches dangerous pattern '$($danger.pattern)'. Reason: $($danger.why)"
        $blockedExclusions.Add($p)
        continue
    }
    $warn = Test-WarnPath $p
    if ($warn) {
        Write-Log $log 'WARN' "$p - matches soft-warn pattern '$($warn.pattern)'. Reason: $($warn.why). Proceeding."
    }
    try {
        Add-MpPreference -ExclusionPath $p -ErrorAction Stop
        Write-Log $log 'APPLY' "Added exclusion: $p"
        $added.Add($p)
        $reverts.Add("Remove-MpPreference -ExclusionPath '$p'")
    } catch {
        Write-Log $log 'ERR' "$p : $($_.Exception.Message)"
    }
}

$revertScript = Join-Path $SnapshotDir 'revert.ps1'
$header = "# Auto-generated by pc-cleaner (defender). Removes exclusions added this run.`n# Never touches RTP status.`n`n"
Set-Content -Path $revertScript -Value ($header + ($reverts -join "`n")) -Encoding UTF8

if ($blockedExclusions.Count -gt 0) {
    $blockedJson = Join-Path $SnapshotDir 'blocked-dangerous-exclusions.json'
    $blockedExclusions | ConvertTo-Json | Set-Content -Path $blockedJson -Encoding UTF8
    Write-Host ""
    Write-Host "Blocked $($blockedExclusions.Count) dangerous exclusion path(s):" -ForegroundColor Yellow
    foreach ($p in $blockedExclusions) { Write-Host "  - $p" -ForegroundColor Yellow }
    Write-Host "See apply.log + data/defender_dangerous_paths.json for the rules." -ForegroundColor DarkGray
}

"===== defender apply done: $($added.Count) exclusions added =====" | Add-Content -Path $log
Write-Host "Added $($added.Count) exclusions"
Write-Host "Revert: $revertScript"
