# Apply: write Win11 explorer UI tweaks. Same shape as apply/privacy.ps1.
# HKCU tweaks don't need admin; HKLM ones do. Falls back gracefully.
# Sets pendingExplorerRestart=true in the run state instead of restarting Explorer inline.

param(
    [Parameter(Mandatory=$true)][string]$Plan,
    [string]$SnapshotDir,
    [switch]$IKnowWhatImDoing
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '..\_lib\common.ps1')

if (-not $SnapshotDir) { $SnapshotDir = New-SnapshotDir -Module 'explorer' }
$log = Join-Path $SnapshotDir 'apply.log'
"===== explorer apply started $(Get-Date -Format o) =====" | Out-File $log -Encoding UTF8

$planData = Get-Content $Plan -Raw | ConvertFrom-Json
$keys     = @($planData.keys)

# ask_user category enforcement — added 2026-07-07. Keys whose category is in
# explorer_keys.json notes.ask_user (classic_menu, file_visibility, theme,
# chat_ui, virtual_desktops) must have confirmed:true. Prevents silent hide of
# the Chat/Teams icon and Task View button.
$sourceJson = Join-Path $PSScriptRoot '..\..\data\explorer_keys.json'
$askCategories = @()
if (Test-Path $sourceJson) {
    $src = Get-Content $sourceJson -Raw | ConvertFrom-Json
    $askCategories = @($src.notes.ask_user)
}
$blockedKeys = New-Object System.Collections.Generic.List[string]

$snap = Join-Path $SnapshotDir 'snapshot.json'
$originalStates = New-Object System.Collections.Generic.List[object]
$reverts = New-Object System.Collections.Generic.List[string]

foreach ($k in $keys) {
    if ($k.category -and ($askCategories -contains $k.category) -and -not $k.confirmed -and -not $IKnowWhatImDoing) {
        Write-Log $log 'BLOCK' "$($k.path) $($k.name) - category '$($k.category)' is in ask_user list; missing confirmed:true. Skipping."
        $blockedKeys.Add("$($k.category):$($k.name)")
        continue
    }
    $original = $null
    $existedBefore = $false
    if (Test-Path $k.path) {
        $item = Get-ItemProperty -Path $k.path -Name $k.name -ErrorAction SilentlyContinue
        if ($item) { $original = $item.$($k.name); $existedBefore = $true }
    }
    $originalStates.Add([PSCustomObject]@{
        Path = $k.path; Name = $k.name; OriginalValue = $original; ExistedBefore = $existedBefore
    })

    # HKLM writes need admin - detect and skip with warning
    if ($k.path -like 'HKLM:*' -and -not (Test-Admin)) {
        Write-Log $log 'SKIP-ADMIN' "$($k.path) $($k.name) - HKLM path but session not elevated"
        continue
    }

    try {
        if (-not (Test-Path $k.path)) { New-Item -Path $k.path -Force | Out-Null }
        # Handle empty-string writes for classic-menu override
        if ($k.type -eq 'String' -and $k.value -eq '') {
            Set-Item -Path $k.path -Value '' -ErrorAction Stop
        } else {
            New-ItemProperty -Path $k.path -Name $k.name -Value $k.value -PropertyType $k.type -Force -ErrorAction Stop | Out-Null
        }
        Write-Log $log 'APPLY' "[$($k.category)] $($k.path) $($k.name) = $($k.value)  (was: $(if($existedBefore){$original}else{'<absent>'}))"

        if ($existedBefore) {
            $reverts.Add("Set-ItemProperty -Path '$($k.path)' -Name '$($k.name)' -Value $original -Type $($k.type)")
        } else {
            $reverts.Add("Remove-ItemProperty -Path '$($k.path)' -Name '$($k.name)' -ErrorAction SilentlyContinue")
        }
    } catch {
        Write-Log $log 'ERR' "$($k.path) $($k.name): $($_.Exception.Message)"
    }
}

$originalStates | ConvertTo-Json | Set-Content $snap -Encoding UTF8

if ($blockedKeys.Count -gt 0) {
    $blockedJson = Join-Path $SnapshotDir 'blocked-ask-user.json'
    $blockedKeys | ConvertTo-Json | Set-Content -Path $blockedJson -Encoding UTF8
    Write-Host ""
    Write-Host "Skipped $($blockedKeys.Count) ask_user key(s) missing confirmation: $($blockedKeys -join ', ')" -ForegroundColor Yellow
}

# Signal to orchestrator that Explorer restart is needed at end of run
$runStateFile = Join-Path (Split-Path $SnapshotDir -Parent) 'run-state.json'
$runState = if (Test-Path $runStateFile) { Get-Content $runStateFile -Raw | ConvertFrom-Json } else { [PSCustomObject]@{} }
$runState | Add-Member -MemberType NoteProperty -Name pendingExplorerRestart -Value $true -Force
$runState | ConvertTo-Json | Set-Content $runStateFile -Encoding UTF8

$revertScript = Join-Path $SnapshotDir 'revert.ps1'
$header = "# Auto-generated by pc-cleaner (explorer). Restart Explorer after running to see changes.`n`n"
$footer = "`n`nStop-Process -Name explorer -Force -ErrorAction SilentlyContinue"
Set-Content -Path $revertScript -Value ($header + ($reverts -join "`n") + $footer) -Encoding UTF8

"===== explorer apply done $(Get-Date -Format o) =====" | Add-Content -Path $log
Write-Host "Snapshot: $snap"
Write-Host "Revert  : $revertScript"
Write-Host "Note    : Explorer restart deferred to orchestrator (pendingExplorerRestart flag set)."
