# Apply: SMBv1 removal, LLMNR off, NetBIOS-over-TCP off, optional DNS/DoH override.
# REQUIRES ADMIN.

param(
    [Parameter(Mandatory=$true)][string]$Plan,
    [string]$SnapshotDir
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '..\_lib\common.ps1')
Assert-Admin

if (-not $SnapshotDir) { $SnapshotDir = New-SnapshotDir -Module 'network' }
$log = Join-Path $SnapshotDir 'apply.log'
"===== network apply started $(Get-Date -Format o) =====" | Out-File $log -Encoding UTF8

$planData = Get-Content $Plan -Raw | ConvertFrom-Json
$reverts = New-Object System.Collections.Generic.List[string]

# Snapshot
$snap = Join-Path $SnapshotDir 'snapshot.json'
$before = [PSCustomObject]@{
    Timestamp = (Get-Date).ToString('o')
    SMB1Feature = (Get-WindowsOptionalFeature -Online -FeatureName SMB1Protocol -ErrorAction SilentlyContinue).State
    DNSServers = @(Get-DnsClientServerAddress -AddressFamily IPv4 | Select-Object InterfaceAlias, ServerAddresses)
}
$before | ConvertTo-Json -Depth 4 | Set-Content $snap -Encoding UTF8

# 1. Remove SMBv1
if ($planData.disableSMBv1) {
    try {
        $f = Get-WindowsOptionalFeature -Online -FeatureName SMB1Protocol
        if ($f.State -eq 'Enabled') {
            Disable-WindowsOptionalFeature -Online -FeatureName SMB1Protocol -NoRestart -ErrorAction Stop | Out-Null
            Write-Log $log 'APPLY' "SMBv1 protocol feature disabled (reboot needed to fully unload)"
            $reverts.Add("Enable-WindowsOptionalFeature -Online -FeatureName SMB1Protocol -NoRestart")
        } else {
            Write-Log $log 'SKIP' "SMBv1 already disabled"
        }
    } catch {
        Write-Log $log 'ERR' "SMBv1: $($_.Exception.Message)"
    }
}

# 2. LLMNR off
if ($planData.disableLLMNR) {
    try {
        $p = 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient'
        if (-not (Test-Path $p)) { New-Item -Path $p -Force | Out-Null }
        $before = (Get-ItemProperty -Path $p -Name EnableMulticast -ErrorAction SilentlyContinue).EnableMulticast
        Set-ItemProperty -Path $p -Name EnableMulticast -Value 0 -Type DWord
        Write-Log $log 'APPLY' "LLMNR disabled via policy (was $before)"
        if ($null -ne $before) {
            $reverts.Add("Set-ItemProperty -Path '$p' -Name EnableMulticast -Value $before -Type DWord")
        } else {
            $reverts.Add("Remove-ItemProperty -Path '$p' -Name EnableMulticast -ErrorAction SilentlyContinue")
        }
    } catch { Write-Log $log 'ERR' "LLMNR: $($_.Exception.Message)" }
}

# 3. NetBIOS over TCP off per adapter
if ($planData.disableNetBIOS) {
    try {
        Get-CimInstance Win32_NetworkAdapterConfiguration -Filter 'IPEnabled=TRUE' | ForEach-Object {
            $adapter = $_.Description
            $before = $_.TcpipNetbiosOptions
            $result = $_ | Invoke-CimMethod -MethodName SetTcpipNetbios -Arguments @{ TcpipNetbios = 2 }  # 2 = Disable
            if ($result.ReturnValue -eq 0) {
                Write-Log $log 'APPLY' "NetBIOS over TCP disabled on: $adapter (was $before)"
                $reverts.Add("Get-CimInstance Win32_NetworkAdapterConfiguration -Filter `"Description='$adapter'`" | Invoke-CimMethod -MethodName SetTcpipNetbios -Arguments @{ TcpipNetbios = $before }")
            } else {
                Write-Log $log 'WARN' "NetBIOS on $adapter : SetTcpipNetbios returned $($result.ReturnValue)"
            }
        }
    } catch { Write-Log $log 'ERR' "NetBIOS: $($_.Exception.Message)" }
}

# 4. Optional DNS override
if ($planData.dnsOverride -and $planData.dnsOverride.ipv4) {
    try {
        $adapters = Get-NetAdapter | Where-Object { $_.Status -eq 'Up' -and $_.HardwareInterface }
        foreach ($a in $adapters) {
            $ifBefore = (Get-DnsClientServerAddress -InterfaceIndex $a.ifIndex -AddressFamily IPv4).ServerAddresses -join ','
            Set-DnsClientServerAddress -InterfaceIndex $a.ifIndex -ServerAddresses $planData.dnsOverride.ipv4
            Write-Log $log 'APPLY' "DNS on $($a.Name) -> $($planData.dnsOverride.ipv4 -join ',')  (was $ifBefore)"
            $reverts.Add("Set-DnsClientServerAddress -InterfaceIndex $($a.ifIndex) -ResetServerAddresses")
        }
    } catch { Write-Log $log 'ERR' "DNS override: $($_.Exception.Message)" }
}

$revertScript = Join-Path $SnapshotDir 'revert.ps1'
$header = "# Auto-generated by pc-cleaner (network). Reverts SMBv1, LLMNR, NetBIOS, DNS.`n`n"
Set-Content -Path $revertScript -Value ($header + ($reverts -join "`n")) -Encoding UTF8

"===== network apply done $(Get-Date -Format o) =====" | Add-Content -Path $log
Write-Host "Snapshot: $snap"
Write-Host "Revert  : $revertScript"
