# Apply: write privacy registry keys from a plan JSON. Exports current values first.
# REQUIRES ADMIN for HKLM writes.
#
# Plan JSON shape:
#   {
#     "keys": [
#       { "path": "HKCU:\\...\\AdvertisingInfo", "name": "Enabled", "type": "DWord", "value": 0, "category": "ad_id", "note": "..." }
#     ]
#   }

param(
    [Parameter(Mandatory=$true)][string]$Plan,
    [string]$SnapshotDir
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '..\_lib\common.ps1')
Assert-Admin

if (-not $SnapshotDir) { $SnapshotDir = New-SnapshotDir -Module 'privacy' }
$log = Join-Path $SnapshotDir 'apply.log'
"===== privacy apply started $(Get-Date -Format o) =====" | Out-File $log -Encoding UTF8

$planData = Get-Content $Plan -Raw | ConvertFrom-Json
$keys     = @($planData.keys)

$snap = Join-Path $SnapshotDir 'snapshot.json'
$originalStates = New-Object System.Collections.Generic.List[object]

$reverts = New-Object System.Collections.Generic.List[string]

foreach ($k in $keys) {
    # Capture original
    $original = $null
    $existedBefore = $false
    if (Test-Path $k.path) {
        $item = Get-ItemProperty -Path $k.path -Name $k.name -ErrorAction SilentlyContinue
        if ($item) { $original = $item.$($k.name); $existedBefore = $true }
    }
    $originalStates.Add([PSCustomObject]@{
        Path = $k.path; Name = $k.name; OriginalValue = $original; ExistedBefore = $existedBefore
    })

    # Ensure path exists, write new value
    try {
        if (-not (Test-Path $k.path)) {
            New-Item -Path $k.path -Force | Out-Null
        }
        New-ItemProperty -Path $k.path -Name $k.name -Value $k.value -PropertyType $k.type -Force -ErrorAction Stop | Out-Null
        Write-Log $log 'APPLY' "$($k.category) - [$($k.path)] $($k.name) = $($k.value)  (was: $(if($existedBefore){$original}else{'<absent>'}))"

        if ($existedBefore) {
            $reverts.Add("Set-ItemProperty -Path '$($k.path)' -Name '$($k.name)' -Value $original -Type $($k.type)")
        } else {
            $reverts.Add("Remove-ItemProperty -Path '$($k.path)' -Name '$($k.name)' -ErrorAction SilentlyContinue")
        }
    } catch {
        Write-Log $log 'ERR' "$($k.path) $($k.name): $($_.Exception.Message)"
    }
}

$originalStates | ConvertTo-Json | Set-Content $snap -Encoding UTF8

# Emit revert script
$revertScript = Join-Path $SnapshotDir 'revert.ps1'
$header = "# Auto-generated by pc-cleaner (privacy). Restore registry keys.`n`n"
Set-Content -Path $revertScript -Value ($header + ($reverts -join "`n")) -Encoding UTF8

"===== privacy apply done $(Get-Date -Format o) =====" | Add-Content -Path $log
Write-Host "Snapshot: $snap"
Write-Host "Revert  : $revertScript"
