# Apply: disable services from a plan JSON. Snapshots first. Emits revert.ps1.
# REQUIRES ADMIN.
#
# Plan JSON shape:
#   {
#     "disable":       ["Spooler", "DiagTrack", ...],
#     "enableManual":  ["ssh-agent"],
#     "enableAuto":    []
#   }

param(
    [Parameter(Mandatory=$true)][string]$Plan,
    [string]$SnapshotDir
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '..\_lib\common.ps1')
Assert-Admin

if (-not $SnapshotDir) { $SnapshotDir = New-SnapshotDir -Module 'services' }
$log = Join-Path $SnapshotDir 'apply.log'
"===== services apply started $(Get-Date -Format o) =====" | Out-File $log -Encoding UTF8

# Snapshot
$snap = Join-Path $SnapshotDir 'snapshot.csv'
Get-Service | Select-Object Name, DisplayName, StartType, Status |
    Export-Csv -Path $snap -NoTypeInformation -Encoding UTF8
Write-Log $log 'SNAP' "Wrote $snap"

$planData = Get-Content $Plan -Raw | ConvertFrom-Json
$disable       = @($planData.disable)
$enableManual  = @($planData.enableManual)
$enableAuto    = @($planData.enableAuto)

$reverts = New-Object System.Collections.Generic.List[string]

foreach ($n in $disable) {
    try {
        $svc = Get-Service -Name $n -ErrorAction Stop
        $originalStartType = $svc.StartType
        if ($svc.Status -eq 'Running') {
            try { Stop-Service -Name $n -Force -ErrorAction Stop } catch {
                Write-Log $log 'WARN' "Could not stop $n : $($_.Exception.Message)"
            }
        }
        try {
            Set-Service -Name $n -StartupType Disabled -ErrorAction Stop
            Write-Log $log 'APPLY' "$n disabled (was $originalStartType)"
        } catch {
            # Fallback for per-user template services + protected keys: registry Start=4
            $regKey = "HKLM:\SYSTEM\CurrentControlSet\Services\$($n -replace '_[a-f0-9]{4,6}$','')"
            if (Test-Path $regKey) {
                try {
                    Set-ItemProperty -Path $regKey -Name Start -Value 4 -Type DWord -ErrorAction Stop
                    Write-Log $log 'APPLY-REG' "$n disabled via registry ($regKey)"
                } catch {
                    Write-Log $log 'ERR' "$n : both Set-Service and registry failed. $($_.Exception.Message)"
                    continue
                }
            } else {
                Write-Log $log 'ERR' "$n : Set-Service failed and no fallback registry key found."
                continue
            }
        }
        $reverts.Add("Set-Service -Name '$n' -StartupType $originalStartType -ErrorAction SilentlyContinue")
    } catch {
        Write-Log $log 'ERR' "$n : $($_.Exception.Message)"
    }
}

foreach ($n in $enableManual) {
    try {
        $svc = Get-Service -Name $n -ErrorAction Stop
        $original = $svc.StartType
        Set-Service -Name $n -StartupType Manual -ErrorAction Stop
        try { Start-Service -Name $n -ErrorAction Stop } catch {}
        Write-Log $log 'APPLY' "$n set Manual + started (was $original)"
        $reverts.Add("Set-Service -Name '$n' -StartupType $original")
    } catch {
        Write-Log $log 'ERR' "$n enableManual : $($_.Exception.Message)"
    }
}

foreach ($n in $enableAuto) {
    try {
        $svc = Get-Service -Name $n -ErrorAction Stop
        $original = $svc.StartType
        Set-Service -Name $n -StartupType Automatic -ErrorAction Stop
        try { Start-Service -Name $n -ErrorAction Stop } catch {}
        Write-Log $log 'APPLY' "$n set Automatic + started (was $original)"
        $reverts.Add("Set-Service -Name '$n' -StartupType $original")
    } catch {
        Write-Log $log 'ERR' "$n enableAuto : $($_.Exception.Message)"
    }
}

# Emit revert script
$revertScript = Join-Path $SnapshotDir 'revert.ps1'
$header = "# Auto-generated by pc-cleaner. Restore services to their state before this apply.`n# Snapshot CSV: $snap`n`n"
$body = $reverts -join "`n"
Set-Content -Path $revertScript -Value ($header + $body) -Encoding UTF8

"===== services apply done $(Get-Date -Format o) =====" | Add-Content -Path $log
Write-Host ""
Write-Host "Snapshot dir: $SnapshotDir"
Write-Host "Revert with : powershell -File $revertScript"
