# Apply: disable startup entries from a plan JSON. Snapshots first.
# REQUIRES ADMIN for HKLM changes and Task Scheduler edits.
#
# Plan JSON shape:
#   {
#     "disable": [
#       { "source": "registry-run", "location": "HKLM:\\...\\Run", "name": "Adobe ARM" },
#       { "source": "startup-folder", "location": "C:\\Users\\...\\Startup", "name": "OneNote.lnk" },
#       { "source": "task-scheduler", "location": "\\Old\\Adobe ARM Update Task", "name": "Adobe ARM Update Task" }
#     ]
#   }

param(
    [Parameter(Mandatory=$true)][string]$Plan,
    [string]$SnapshotDir
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '..\_lib\common.ps1')
Assert-Admin

if (-not $SnapshotDir) { $SnapshotDir = New-SnapshotDir -Module 'startup' }
$log = Join-Path $SnapshotDir 'apply.log'
"===== startup apply started $(Get-Date -Format o) =====" | Out-File $log -Encoding UTF8

$planData = Get-Content $Plan -Raw | ConvertFrom-Json
$disable  = @($planData.disable)

# Snapshot current state via diagnose script for reference
$snap = Join-Path $SnapshotDir 'snapshot.json'
& (Join-Path $PSScriptRoot '..\diagnose\startup.ps1') | Set-Content $snap -Encoding UTF8
Write-Log $log 'SNAP' "Wrote $snap"

$reverts = New-Object System.Collections.Generic.List[string]

foreach ($item in $disable) {
    try {
        switch ($item.source) {
            'registry-run' {
                # Save current value + delete
                $val = (Get-ItemProperty -Path $item.location -Name $item.name -ErrorAction Stop).$($item.name)
                Remove-ItemProperty -Path $item.location -Name $item.name -ErrorAction Stop
                Write-Log $log 'APPLY' "removed registry-run: [$($item.location)] $($item.name)"
                $reverts.Add("Set-ItemProperty -Path '$($item.location)' -Name '$($item.name)' -Value '$val' -Type String")
            }
            'startup-folder' {
                $srcPath = $item.command
                if (-not $srcPath) { $srcPath = Join-Path $item.location $item.name }
                if (Test-Path $srcPath) {
                    # Move to snapshot dir; revert = move back
                    $backup = Join-Path $SnapshotDir "startup-folder-backup"
                    if (-not (Test-Path $backup)) { New-Item -ItemType Directory -Path $backup -Force | Out-Null }
                    $dest = Join-Path $backup $item.name
                    Move-Item -Path $srcPath -Destination $dest -Force
                    Write-Log $log 'APPLY' "moved startup-folder entry to backup: $srcPath -> $dest"
                    $reverts.Add("Move-Item -Path '$dest' -Destination '$srcPath' -Force")
                }
            }
            'task-scheduler' {
                Disable-ScheduledTask -TaskPath (Split-Path $item.location -Parent) -TaskName $item.name -ErrorAction Stop | Out-Null
                Write-Log $log 'APPLY' "disabled scheduled task: $($item.location)"
                $reverts.Add("Enable-ScheduledTask -TaskPath '$(Split-Path $item.location -Parent)' -TaskName '$($item.name)'")
            }
            default {
                Write-Log $log 'WARN' "unknown source: $($item.source)"
            }
        }
    } catch {
        Write-Log $log 'ERR' "$($item.source) $($item.name): $($_.Exception.Message)"
    }
}

# Emit revert script
$revertScript = Join-Path $SnapshotDir 'revert.ps1'
$header = "# Auto-generated by pc-cleaner (startup). Restore startup entries.`n`n"
Set-Content -Path $revertScript -Value ($header + ($reverts -join "`n")) -Encoding UTF8

"===== startup apply done $(Get-Date -Format o) =====" | Add-Content -Path $log
Write-Host "Snapshot dir: $SnapshotDir"
Write-Host "Revert with : powershell -File $revertScript"
