# Apply: hide tray icons + unpin taskbar apps from a plan JSON.
# NO admin needed for HKCU changes.
# Signals pendingExplorerRestart to orchestrator for pinned-app changes to take effect.
#
# Plan shape:
#   {
#     "hideTrayIcons": ["path\\to\\exe1", "path\\to\\exe2"],
#     "unpinApps":     ["LinkNameWithoutExt", ...]
#   }

param(
    [Parameter(Mandatory=$true)][string]$Plan,
    [string]$SnapshotDir
)

$ErrorActionPreference = 'Continue'
. (Join-Path $PSScriptRoot '..\_lib\common.ps1')

if (-not $SnapshotDir) { $SnapshotDir = New-SnapshotDir -Module 'tray-taskbar' }
$log = Join-Path $SnapshotDir 'apply.log'
"===== tray-taskbar apply started $(Get-Date -Format o) =====" | Out-File $log -Encoding UTF8

$planData = Get-Content $Plan -Raw | ConvertFrom-Json
$reverts = New-Object System.Collections.Generic.List[string]

# 1. Tray icons: set IsPromoted=0 in NotifyIconSettings
$trayKey = 'HKCU:\Control Panel\NotifyIconSettings'
if (Test-Path $trayKey) {
    $before = @{}
    Get-ChildItem $trayKey | ForEach-Object {
        $p = Get-ItemProperty $_.PSPath
        if ($p.ExecutablePath) {
            $before[$p.ExecutablePath] = $p.IsPromoted
        }
    }
    (Get-Content (Join-Path $SnapshotDir 'snapshot-tray.json' 2>$null) 2>$null) | Out-Null
    $before | ConvertTo-Json | Set-Content (Join-Path $SnapshotDir 'snapshot-tray.json') -Encoding UTF8

    foreach ($exe in @($planData.hideTrayIcons)) {
        Get-ChildItem $trayKey | ForEach-Object {
            $p = Get-ItemProperty $_.PSPath
            if ($p.ExecutablePath -eq $exe) {
                $wasPromoted = $p.IsPromoted
                Set-ItemProperty -Path $_.PSPath -Name IsPromoted -Value 0 -Type DWord -ErrorAction SilentlyContinue
                Write-Log $log 'TRAY-HIDE' "$exe (IsPromoted $wasPromoted -> 0)"
                $reverts.Add("Set-ItemProperty -Path '$($_.PSPath)' -Name IsPromoted -Value $wasPromoted -Type DWord")
            }
        }
    }
}

# 2. Unpin taskbar apps: delete the .lnk in PinnedItems
$pinnedFolder = "$env:APPDATA\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar"
$backupDir = Join-Path $SnapshotDir 'unpinned-lnk-backup'
New-Item -ItemType Directory -Path $backupDir -Force | Out-Null

foreach ($linkName in @($planData.unpinApps)) {
    $lnk = Join-Path $pinnedFolder "$linkName.lnk"
    if (Test-Path $lnk) {
        try {
            Move-Item -Path $lnk -Destination $backupDir -Force -ErrorAction Stop
            Write-Log $log 'UNPIN' "$linkName -> backup"
            $reverts.Add("Move-Item -Path '$(Join-Path $backupDir "$linkName.lnk")' -Destination '$lnk' -Force")
        } catch {
            Write-Log $log 'ERR' "unpin $linkName : $($_.Exception.Message)"
        }
    }
}

# Delete the pin cache blob so Explorer rebuilds it from remaining .lnk files.
# HKCU:\...\FavoritesResolve - Win11 stores pin metadata here. Deleting it forces rebuild.
$favResolve = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband'
if ((Test-Path $favResolve) -and $planData.unpinApps.Count -gt 0) {
    try {
        # Snapshot the whole key
        $snap = Join-Path $SnapshotDir 'taskband-backup.reg'
        reg export $($favResolve -replace 'HKCU:','HKEY_CURRENT_USER') $snap /y 2>&1 | Out-Null
        # Remove FavoritesResolve value to force rebuild
        Remove-ItemProperty -Path $favResolve -Name FavoritesResolve -ErrorAction SilentlyContinue
        Remove-ItemProperty -Path $favResolve -Name Favorites -ErrorAction SilentlyContinue
        Write-Log $log 'PIN-BLOB' "Reset Taskband pin cache (backed up to $snap)"
        $reverts.Add("reg import '$snap'")
    } catch {
        Write-Log $log 'WARN' "Could not reset Taskband cache: $($_.Exception.Message)"
    }
}

# Signal orchestrator to restart Explorer
$runStateFile = Join-Path (Split-Path $SnapshotDir -Parent) 'run-state.json'
$runState = if (Test-Path $runStateFile) { Get-Content $runStateFile -Raw | ConvertFrom-Json } else { [PSCustomObject]@{} }
$runState | Add-Member -MemberType NoteProperty -Name pendingExplorerRestart -Value $true -Force
$runState | ConvertTo-Json | Set-Content $runStateFile -Encoding UTF8

$revertScript = Join-Path $SnapshotDir 'revert.ps1'
$header = "# Auto-generated by pc-cleaner (tray-taskbar). Restore tray promotion + pinned apps.`n# Explorer restart required to take effect.`n`n"
$footer = "`n`nStop-Process -Name explorer -Force -ErrorAction SilentlyContinue`nStart-Process explorer"
Set-Content -Path $revertScript -Value ($header + ($reverts -join "`n") + $footer) -Encoding UTF8

"===== tray-taskbar apply done =====" | Add-Content -Path $log
Write-Host "Log   : $log"
Write-Host "Revert: $revertScript"
Write-Host "Note  : Explorer restart deferred to orchestrator."
