# Apply: uninstall user-selected apps from unused-apps diagnose.
# Uses QuietUninstallString when present; falls back to UninstallString + silent flags
# looked up in data/silent_uninstall_flags.json.
# REQUIRES ADMIN for HKLM uninstall entries.

param(
    [Parameter(Mandatory=$true)][string]$Plan,
    [string]$SnapshotDir
)

$ErrorActionPreference = 'Continue'
. (Join-Path $PSScriptRoot '..\_lib\common.ps1')

if (-not $SnapshotDir) { $SnapshotDir = New-SnapshotDir -Module 'unused-apps' }
$log = Join-Path $SnapshotDir 'apply.log'
"===== unused-apps apply started $(Get-Date -Format o) =====" | Out-File $log -Encoding UTF8

$planData = Get-Content $Plan -Raw | ConvertFrom-Json
$apps = @($planData.uninstall)   # list of { DisplayName, UninstallString, QuietUninstallString, Publisher }

$dataDir = Join-Path $PSScriptRoot '..\..\data'
$flagsFile = Join-Path $dataDir 'silent_uninstall_flags.json'
$silentFlags = if (Test-Path $flagsFile) { Get-Content $flagsFile -Raw | ConvertFrom-Json } else { $null }

# Snapshot
$snap = Join-Path $SnapshotDir 'snapshot.json'
$apps | ConvertTo-Json -Depth 4 | Set-Content $snap -Encoding UTF8

$reverts = New-Object System.Collections.Generic.List[string]
$successCount = 0

foreach ($a in $apps) {
    $cmd = $a.QuietUninstallString
    if (-not $cmd) {
        $cmd = $a.UninstallString
        # Try to append silent flags detected from installer type
        if ($silentFlags -and $cmd) {
            $installerType = 'unknown'
            if ($cmd -match 'msiexec') { $installerType = 'msi' }
            elseif ($cmd -match 'unins\d+\.exe|UninstallString.*inno') { $installerType = 'inno' }
            elseif ($cmd -match 'uninstall\.exe.*nsis|Uninstaller\.exe') { $installerType = 'nsis' }
            elseif ($cmd -match 'setup\.exe') { $installerType = 'installshield' }
            if ($installerType -ne 'unknown' -and $silentFlags.installers.PSObject.Properties.Name -contains $installerType) {
                $flag = $silentFlags.installers.$installerType.flag
                if ($cmd -notmatch [regex]::Escape($flag)) { $cmd = "$cmd $flag" }
            }
        }
    }
    if (-not $cmd) {
        Write-Log $log 'SKIP' "$($a.DisplayName): no uninstall command"
        continue
    }

    try {
        # Extract exe + args
        $exe = ''; $args = ''
        if ($cmd -match '^"([^"]+)"\s*(.*)$') { $exe = $Matches[1]; $args = $Matches[2] }
        elseif ($cmd -match '^(\S+)\s*(.*)$') { $exe = $Matches[1]; $args = $Matches[2] }
        else { $exe = $cmd }

        # Kill processes belonging to this app first
        if ($a.DisplayName) {
            Get-Process -ErrorAction SilentlyContinue | Where-Object {
                $_.MainWindowTitle -match [regex]::Escape($a.DisplayName) -or $_.ProcessName -match [regex]::Escape(($a.DisplayName -split ' ')[0])
            } | ForEach-Object {
                Write-Log $log 'KILL' "$($_.ProcessName) (PID $($_.Id)) for $($a.DisplayName)"
                Stop-Process -Id $_.Id -Force -ErrorAction SilentlyContinue
            }
        }

        Write-Log $log 'RUN' "$($a.DisplayName): $exe $args"
        $p = Start-Process -FilePath $exe -ArgumentList $args -Wait -PassThru -ErrorAction Stop
        if ($p.ExitCode -in @(0, 1605, 3010)) {   # 0=OK, 1605=absent, 3010=reboot needed
            Write-Log $log 'DONE' "$($a.DisplayName) exit $($p.ExitCode)"
            $successCount++
        } else {
            Write-Log $log 'WARN' "$($a.DisplayName) exit $($p.ExitCode) - may not have uninstalled cleanly"
        }
        $reverts.Add("# $($a.DisplayName): no automatic reinstall. Was published by $($a.Publisher).")
    } catch {
        Write-Log $log 'ERR' "$($a.DisplayName): $($_.Exception.Message)"
    }
}

$revertScript = Join-Path $SnapshotDir 'revert.ps1'
$header = "# Auto-generated by pc-cleaner (unused-apps). Uninstalls are IRREVERSIBLE by this script.`n# List of apps removed (reinstall manually via publisher's site or winget):`n"
Set-Content -Path $revertScript -Value ($header + ($reverts -join "`n")) -Encoding UTF8

"===== unused-apps apply done: $successCount / $($apps.Count) uninstalled =====" | Add-Content -Path $log
Write-Host "Uninstalled: $successCount / $($apps.Count)"
Write-Host "Log        : $log"
